[package]
name = "argon2_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = { version = "0.4.1", features = ["std"] }
rand = { version = "0.8.5", features = ["std_rng"] }
